### ISSUE TITLE
Feature: RiotClient

### ISSUE THREAD

**Issue by Neinndall** [PenguLoader/PenguLoader#76]
Being able to navigate and investigate the RiotClient should be another option. There is a lot of assets and other stuff in this part of the client

![image](https://github.com/PenguLoader/PenguLoader/assets/66384195/445cf645-4571-4f54-95ad-37394f972aaf)

**Comment by nomi-san** [comment]
> navigate

What do you mean, log out your LoL account and nagivate to RiotClient login screen?

> investigate ... There is a lot of assets and other stuff in this part of the client

There is another project can help you to do it: [nomi-san/RitoClient](https://github.com/nomi-san/RitoClient).

**Comment by Neinndall** [comment]
I looked at it but for me it's more complicated, since this is easier since I'm using the `.exe `and when I enter the client I just do: `shift + i` and run the dev tool, it's easier XD!

**Comment by nomi-san** [comment]
I'm sure you dont know how to build it. Check out the Release page to download.

> assets and api endpoints

Seems you are confused betwwen DevTools tabs/features and [RiotClient API](https://riotclient.nomi.dev/) enpoints.

**Comment by Neinndall** [comment]
Was easy thx for this!

Nomi, u cant build RiotClient tool into .exe like pengu?

**Comment by BakaFT** [comment]
> Nomi, cant u build RiotClient tool into `.exe portable` like pengu?

First you need to know difference between `Core` and `Loader`.

In `PenguLoader`:
- `Core` is the code that compiled into a `dll` file and waiting to be `injected` into `LeagueClient`.
- `Loader`  is a tool that activate/deactivate the injecting through IFEO settings.

Since RiotClient is the same as LeagueClient in low-level. So with a little changes it can apply to RiotClient.

[RitoClient](https://github.com/nomi-san/RitoClient) is a **rushed** port cuz it's for debugging purpose only, so he didn't port the `Loader`.

**Those two `.bat` is just doing the same thing as `Loader` do and it's enough** ( we dont have plugins/super low spec/ stuff now).
